//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 11:33:23 AM CET 
//


package eu.opends.opendrive.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for access.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="access">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="car"/>
 *     &lt;enumeration value="women"/>
 *     &lt;enumeration value="handicapped"/>
 *     &lt;enumeration value="bus"/>
 *     &lt;enumeration value="truck"/>
 *     &lt;enumeration value="electric"/>
 *     &lt;enumeration value="residents"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "access")
@XmlEnum
public enum Access {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("car")
    CAR("car"),
    @XmlEnumValue("women")
    WOMEN("women"),
    @XmlEnumValue("handicapped")
    HANDICAPPED("handicapped"),
    @XmlEnumValue("bus")
    BUS("bus"),
    @XmlEnumValue("truck")
    TRUCK("truck"),
    @XmlEnumValue("electric")
    ELECTRIC("electric"),
    @XmlEnumValue("residents")
    RESIDENTS("residents");
    private final String value;

    Access(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Access fromValue(String v) {
        for (Access c: Access.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
