//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 11:33:23 AM CET 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for centerLane complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="centerLane">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="predecessor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="successor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="roadMark" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="line" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="rule" type="{}rule" />
 *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="type" type="{}roadmarkType" />
 *                 &lt;attribute name="weight" type="{}weight" />
 *                 &lt;attribute name="color" type="{}color" />
 *                 &lt;attribute name="material" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="laneChange" type="{}laneChange" />
 *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" type="{}laneType" />
 *       &lt;attribute name="level" type="{}singleSide" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "centerLane", propOrder = {
    "link",
    "roadMark",
    "userData",
    "include"
})
public class CenterLane {

    protected CenterLane.Link link;
    protected List<CenterLane.RoadMark> roadMark;
    protected List<UserData> userData;
    protected List<Include> include;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "type")
    protected LaneType type;
    @XmlAttribute(name = "level")
    protected SingleSide level;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link CenterLane.Link }
     *     
     */
    public CenterLane.Link getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenterLane.Link }
     *     
     */
    public void setLink(CenterLane.Link value) {
        this.link = value;
    }

    /**
     * Gets the value of the roadMark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roadMark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoadMark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CenterLane.RoadMark }
     * 
     * 
     */
    public List<CenterLane.RoadMark> getRoadMark() {
        if (roadMark == null) {
            roadMark = new ArrayList<CenterLane.RoadMark>();
        }
        return this.roadMark;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserData }
     * 
     * 
     */
    public List<UserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<UserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * 
     * 
     */
    public List<Include> getInclude() {
        if (include == null) {
            include = new ArrayList<Include>();
        }
        return this.include;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LaneType }
     *     
     */
    public LaneType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaneType }
     *     
     */
    public void setType(LaneType value) {
        this.type = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSide }
     *     
     */
    public SingleSide getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSide }
     *     
     */
    public void setLevel(SingleSide value) {
        this.level = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="predecessor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="successor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "predecessor",
        "successor",
        "userData",
        "include"
    })
    public static class Link {

        protected CenterLane.Link.Predecessor predecessor;
        protected CenterLane.Link.Successor successor;
        protected List<UserData> userData;
        protected List<Include> include;

        /**
         * Gets the value of the predecessor property.
         * 
         * @return
         *     possible object is
         *     {@link CenterLane.Link.Predecessor }
         *     
         */
        public CenterLane.Link.Predecessor getPredecessor() {
            return predecessor;
        }

        /**
         * Sets the value of the predecessor property.
         * 
         * @param value
         *     allowed object is
         *     {@link CenterLane.Link.Predecessor }
         *     
         */
        public void setPredecessor(CenterLane.Link.Predecessor value) {
            this.predecessor = value;
        }

        /**
         * Gets the value of the successor property.
         * 
         * @return
         *     possible object is
         *     {@link CenterLane.Link.Successor }
         *     
         */
        public CenterLane.Link.Successor getSuccessor() {
            return successor;
        }

        /**
         * Sets the value of the successor property.
         * 
         * @param value
         *     allowed object is
         *     {@link CenterLane.Link.Successor }
         *     
         */
        public void setSuccessor(CenterLane.Link.Successor value) {
            this.successor = value;
        }

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Predecessor {

            @XmlAttribute(name = "id")
            protected Integer id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Successor {

            @XmlAttribute(name = "id")
            protected Integer id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="line" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="rule" type="{}rule" />
     *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="type" type="{}roadmarkType" />
     *       &lt;attribute name="weight" type="{}weight" />
     *       &lt;attribute name="color" type="{}color" />
     *       &lt;attribute name="material" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="laneChange" type="{}laneChange" />
     *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "centerLaneRoadMarkType",
        "userData",
        "include"
    })
    public static class RoadMark {

        @XmlElement(name = "type")
        protected CenterLane.RoadMark.Type centerLaneRoadMarkType;
        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "type")
        protected RoadmarkType type;
        @XmlAttribute(name = "weight")
        protected Weight weight;
        @XmlAttribute(name = "color")
        protected Color color;
        @XmlAttribute(name = "material")
        protected String material;
        @XmlAttribute(name = "width")
        protected Double width;
        @XmlAttribute(name = "laneChange")
        protected LaneChange laneChange;
        @XmlAttribute(name = "height")
        protected Double height;

        /**
         * Gets the value of the centerLaneRoadMarkType property.
         * 
         * @return
         *     possible object is
         *     {@link CenterLane.RoadMark.Type }
         *     
         */
        public CenterLane.RoadMark.Type getCenterLaneRoadMarkType() {
            return centerLaneRoadMarkType;
        }

        /**
         * Sets the value of the centerLaneRoadMarkType property.
         * 
         * @param value
         *     allowed object is
         *     {@link CenterLane.RoadMark.Type }
         *     
         */
        public void setCenterLaneRoadMarkType(CenterLane.RoadMark.Type value) {
            this.centerLaneRoadMarkType = value;
        }

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link RoadmarkType }
         *     
         */
        public RoadmarkType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoadmarkType }
         *     
         */
        public void setType(RoadmarkType value) {
            this.type = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link Weight }
         *     
         */
        public Weight getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Weight }
         *     
         */
        public void setWeight(Weight value) {
            this.weight = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link Color }
         *     
         */
        public Color getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link Color }
         *     
         */
        public void setColor(Color value) {
            this.color = value;
        }

        /**
         * Gets the value of the material property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterial() {
            return material;
        }

        /**
         * Sets the value of the material property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterial(String value) {
            this.material = value;
        }

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setWidth(Double value) {
            this.width = value;
        }

        /**
         * Gets the value of the laneChange property.
         * 
         * @return
         *     possible object is
         *     {@link LaneChange }
         *     
         */
        public LaneChange getLaneChange() {
            return laneChange;
        }

        /**
         * Sets the value of the laneChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LaneChange }
         *     
         */
        public void setLaneChange(LaneChange value) {
            this.laneChange = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setHeight(Double value) {
            this.height = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="line" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="rule" type="{}rule" />
         *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "line"
        })
        public static class Type {

            @XmlElement(required = true)
            protected List<CenterLane.RoadMark.Type.Line> line;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "width")
            protected Double width;

            /**
             * Gets the value of the line property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the line property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CenterLane.RoadMark.Type.Line }
             * 
             * 
             */
            public List<CenterLane.RoadMark.Type.Line> getLine() {
                if (line == null) {
                    line = new ArrayList<CenterLane.RoadMark.Type.Line>();
                }
                return this.line;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setWidth(Double value) {
                this.width = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="rule" type="{}rule" />
             *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Line {

                @XmlAttribute(name = "length")
                protected Double length;
                @XmlAttribute(name = "space")
                protected Double space;
                @XmlAttribute(name = "tOffset")
                protected Double tOffset;
                @XmlAttribute(name = "sOffset")
                protected Double sOffset;
                @XmlAttribute(name = "rule")
                protected Rule rule;
                @XmlAttribute(name = "width")
                protected Double width;

                /**
                 * Gets the value of the length property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getLength() {
                    return length;
                }

                /**
                 * Sets the value of the length property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setLength(Double value) {
                    this.length = value;
                }

                /**
                 * Gets the value of the space property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getSpace() {
                    return space;
                }

                /**
                 * Sets the value of the space property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setSpace(Double value) {
                    this.space = value;
                }

                /**
                 * Gets the value of the tOffset property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getTOffset() {
                    return tOffset;
                }

                /**
                 * Sets the value of the tOffset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setTOffset(Double value) {
                    this.tOffset = value;
                }

                /**
                 * Gets the value of the sOffset property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getSOffset() {
                    return sOffset;
                }

                /**
                 * Sets the value of the sOffset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setSOffset(Double value) {
                    this.sOffset = value;
                }

                /**
                 * Gets the value of the rule property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Rule }
                 *     
                 */
                public Rule getRule() {
                    return rule;
                }

                /**
                 * Sets the value of the rule property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Rule }
                 *     
                 */
                public void setRule(Rule value) {
                    this.rule = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setWidth(Double value) {
                    this.width = value;
                }

            }

        }

    }

}
