//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 11:33:23 AM CET 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lane complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lane">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="predecessor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="successor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="width" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="c" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="border" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="c" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                   &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="roadMark" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="line" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="rule" type="{}rule" />
 *                                     &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="type" type="{}roadmarkType" />
 *                 &lt;attribute name="weight" type="{}weight" />
 *                 &lt;attribute name="color" type="{}color" />
 *                 &lt;attribute name="material" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="laneChange" type="{}laneChange" />
 *                 &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="material" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="surface" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="friction" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="roughness" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="visibility" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="forward" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="back" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="left" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="right" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="speed" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="unit" type="{}unit" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="access" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="restriction" type="{}restriction" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="height" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="inner" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="outer" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rule" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" type="{}laneType" />
 *       &lt;attribute name="level" type="{}singleSide" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lane", propOrder = {
    "link",
    "width",
    "border",
    "roadMark",
    "material",
    "visibility",
    "speed",
    "access",
    "height",
    "rule",
    "userData",
    "include"
})
public class Lane {

    protected Lane.Link link;
    protected List<Lane.Width> width;
    protected List<Lane.Border> border;
    protected List<Lane.RoadMark> roadMark;
    protected List<Lane.Material> material;
    protected List<Lane.Visibility> visibility;
    protected List<Lane.Speed> speed;
    protected List<Lane.Access> access;
    protected List<Lane.Height> height;
    protected List<Lane.Rule> rule;
    protected List<UserData> userData;
    protected List<Include> include;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "type")
    protected LaneType type;
    @XmlAttribute(name = "level")
    protected SingleSide level;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link Lane.Link }
     *     
     */
    public Lane.Link getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lane.Link }
     *     
     */
    public void setLink(Lane.Link value) {
        this.link = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the width property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Width }
     * 
     * 
     */
    public List<Lane.Width> getWidth() {
        if (width == null) {
            width = new ArrayList<Lane.Width>();
        }
        return this.width;
    }

    /**
     * Gets the value of the border property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the border property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBorder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Border }
     * 
     * 
     */
    public List<Lane.Border> getBorder() {
        if (border == null) {
            border = new ArrayList<Lane.Border>();
        }
        return this.border;
    }

    /**
     * Gets the value of the roadMark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roadMark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoadMark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.RoadMark }
     * 
     * 
     */
    public List<Lane.RoadMark> getRoadMark() {
        if (roadMark == null) {
            roadMark = new ArrayList<Lane.RoadMark>();
        }
        return this.roadMark;
    }

    /**
     * Gets the value of the material property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the material property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Material }
     * 
     * 
     */
    public List<Lane.Material> getMaterial() {
        if (material == null) {
            material = new ArrayList<Lane.Material>();
        }
        return this.material;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visibility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisibility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Visibility }
     * 
     * 
     */
    public List<Lane.Visibility> getVisibility() {
        if (visibility == null) {
            visibility = new ArrayList<Lane.Visibility>();
        }
        return this.visibility;
    }

    /**
     * Gets the value of the speed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Speed }
     * 
     * 
     */
    public List<Lane.Speed> getSpeed() {
        if (speed == null) {
            speed = new ArrayList<Lane.Speed>();
        }
        return this.speed;
    }

    /**
     * Gets the value of the access property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the access property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Access }
     * 
     * 
     */
    public List<Lane.Access> getAccess() {
        if (access == null) {
            access = new ArrayList<Lane.Access>();
        }
        return this.access;
    }

    /**
     * Gets the value of the height property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the height property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Height }
     * 
     * 
     */
    public List<Lane.Height> getHeight() {
        if (height == null) {
            height = new ArrayList<Lane.Height>();
        }
        return this.height;
    }

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lane.Rule }
     * 
     * 
     */
    public List<Lane.Rule> getRule() {
        if (rule == null) {
            rule = new ArrayList<Lane.Rule>();
        }
        return this.rule;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserData }
     * 
     * 
     */
    public List<UserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<UserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * 
     * 
     */
    public List<Include> getInclude() {
        if (include == null) {
            include = new ArrayList<Include>();
        }
        return this.include;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LaneType }
     *     
     */
    public LaneType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaneType }
     *     
     */
    public void setType(LaneType value) {
        this.type = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSide }
     *     
     */
    public SingleSide getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSide }
     *     
     */
    public void setLevel(SingleSide value) {
        this.level = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="restriction" type="{}restriction" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Access {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "restriction")
        protected Restriction restriction;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the restriction property.
         * 
         * @return
         *     possible object is
         *     {@link Restriction }
         *     
         */
        public Restriction getRestriction() {
            return restriction;
        }

        /**
         * Sets the value of the restriction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Restriction }
         *     
         */
        public void setRestriction(Restriction value) {
            this.restriction = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="c" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Border {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "a")
        protected Double a;
        @XmlAttribute(name = "b")
        protected Double b;
        @XmlAttribute(name = "c")
        protected Double c;
        @XmlAttribute(name = "d")
        protected Double d;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the a property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getA() {
            return a;
        }

        /**
         * Sets the value of the a property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setA(Double value) {
            this.a = value;
        }

        /**
         * Gets the value of the b property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getB() {
            return b;
        }

        /**
         * Sets the value of the b property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setB(Double value) {
            this.b = value;
        }

        /**
         * Gets the value of the c property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getC() {
            return c;
        }

        /**
         * Sets the value of the c property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setC(Double value) {
            this.c = value;
        }

        /**
         * Gets the value of the d property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getD() {
            return d;
        }

        /**
         * Sets the value of the d property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setD(Double value) {
            this.d = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="inner" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="outer" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Height {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "inner")
        protected Double inner;
        @XmlAttribute(name = "outer")
        protected Double outer;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the inner property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getInner() {
            return inner;
        }

        /**
         * Sets the value of the inner property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setInner(Double value) {
            this.inner = value;
        }

        /**
         * Gets the value of the outer property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getOuter() {
            return outer;
        }

        /**
         * Sets the value of the outer property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setOuter(Double value) {
            this.outer = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="predecessor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="successor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "predecessor",
        "successor",
        "userData",
        "include"
    })
    public static class Link {

        protected Lane.Link.Predecessor predecessor;
        protected Lane.Link.Successor successor;
        protected List<UserData> userData;
        protected List<Include> include;

        /**
         * Gets the value of the predecessor property.
         * 
         * @return
         *     possible object is
         *     {@link Lane.Link.Predecessor }
         *     
         */
        public Lane.Link.Predecessor getPredecessor() {
            return predecessor;
        }

        /**
         * Sets the value of the predecessor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Lane.Link.Predecessor }
         *     
         */
        public void setPredecessor(Lane.Link.Predecessor value) {
            this.predecessor = value;
        }

        /**
         * Gets the value of the successor property.
         * 
         * @return
         *     possible object is
         *     {@link Lane.Link.Successor }
         *     
         */
        public Lane.Link.Successor getSuccessor() {
            return successor;
        }

        /**
         * Sets the value of the successor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Lane.Link.Successor }
         *     
         */
        public void setSuccessor(Lane.Link.Successor value) {
            this.successor = value;
        }

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Predecessor {

            @XmlAttribute(name = "id")
            protected Integer id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Successor {

            @XmlAttribute(name = "id")
            protected Integer id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setId(Integer value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="surface" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="friction" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="roughness" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Material {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "surface")
        protected String surface;
        @XmlAttribute(name = "friction")
        protected Double friction;
        @XmlAttribute(name = "roughness")
        protected Double roughness;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the surface property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSurface() {
            return surface;
        }

        /**
         * Sets the value of the surface property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSurface(String value) {
            this.surface = value;
        }

        /**
         * Gets the value of the friction property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getFriction() {
            return friction;
        }

        /**
         * Sets the value of the friction property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setFriction(Double value) {
            this.friction = value;
        }

        /**
         * Gets the value of the roughness property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getRoughness() {
            return roughness;
        }

        /**
         * Sets the value of the roughness property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setRoughness(Double value) {
            this.roughness = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="line" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="rule" type="{}rule" />
     *                           &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="type" type="{}roadmarkType" />
     *       &lt;attribute name="weight" type="{}weight" />
     *       &lt;attribute name="color" type="{}color" />
     *       &lt;attribute name="material" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="laneChange" type="{}laneChange" />
     *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "laneRoadMarkType",
        "userData",
        "include"
    })
    public static class RoadMark {

        @XmlElement(name = "type")
        protected Lane.RoadMark.Type laneRoadMarkType;
        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "type")
        protected RoadmarkType type;
        @XmlAttribute(name = "weight")
        protected Weight weight;
        @XmlAttribute(name = "color")
        protected Color color;
        @XmlAttribute(name = "material")
        protected String material;
        @XmlAttribute(name = "width")
        protected Double width;
        @XmlAttribute(name = "laneChange")
        protected LaneChange laneChange;
        @XmlAttribute(name = "height")
        protected Double height;

        /**
         * Gets the value of the laneRoadMarkType property.
         * 
         * @return
         *     possible object is
         *     {@link Lane.RoadMark.Type }
         *     
         */
        public Lane.RoadMark.Type getLaneRoadMarkType() {
            return laneRoadMarkType;
        }

        /**
         * Sets the value of the laneRoadMarkType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Lane.RoadMark.Type }
         *     
         */
        public void setLaneRoadMarkType(Lane.RoadMark.Type value) {
            this.laneRoadMarkType = value;
        }

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link RoadmarkType }
         *     
         */
        public RoadmarkType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link RoadmarkType }
         *     
         */
        public void setType(RoadmarkType value) {
            this.type = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link Weight }
         *     
         */
        public Weight getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Weight }
         *     
         */
        public void setWeight(Weight value) {
            this.weight = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link Color }
         *     
         */
        public Color getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link Color }
         *     
         */
        public void setColor(Color value) {
            this.color = value;
        }

        /**
         * Gets the value of the material property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterial() {
            return material;
        }

        /**
         * Sets the value of the material property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterial(String value) {
            this.material = value;
        }

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setWidth(Double value) {
            this.width = value;
        }

        /**
         * Gets the value of the laneChange property.
         * 
         * @return
         *     possible object is
         *     {@link LaneChange }
         *     
         */
        public LaneChange getLaneChange() {
            return laneChange;
        }

        /**
         * Sets the value of the laneChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LaneChange }
         *     
         */
        public void setLaneChange(LaneChange value) {
            this.laneChange = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setHeight(Double value) {
            this.height = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="line" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="rule" type="{}rule" />
         *                 &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "line"
        })
        public static class Type {

            @XmlElement(required = true)
            protected List<Lane.RoadMark.Type.Line> line;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "width")
            protected Double width;

            /**
             * Gets the value of the line property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the line property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Lane.RoadMark.Type.Line }
             * 
             * 
             */
            public List<Lane.RoadMark.Type.Line> getLine() {
                if (line == null) {
                    line = new ArrayList<Lane.RoadMark.Type.Line>();
                }
                return this.line;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the width property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getWidth() {
                return width;
            }

            /**
             * Sets the value of the width property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setWidth(Double value) {
                this.width = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="space" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="rule" type="{}rule" />
             *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Line {

                @XmlAttribute(name = "length")
                protected Double length;
                @XmlAttribute(name = "space")
                protected Double space;
                @XmlAttribute(name = "tOffset")
                protected Double tOffset;
                @XmlAttribute(name = "sOffset")
                protected Double sOffset;
                @XmlAttribute(name = "rule")
                protected eu.opends.opendrive.data.Rule rule;
                @XmlAttribute(name = "width")
                protected Double width;

                /**
                 * Gets the value of the length property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getLength() {
                    return length;
                }

                /**
                 * Sets the value of the length property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setLength(Double value) {
                    this.length = value;
                }

                /**
                 * Gets the value of the space property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getSpace() {
                    return space;
                }

                /**
                 * Sets the value of the space property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setSpace(Double value) {
                    this.space = value;
                }

                /**
                 * Gets the value of the tOffset property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getTOffset() {
                    return tOffset;
                }

                /**
                 * Sets the value of the tOffset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setTOffset(Double value) {
                    this.tOffset = value;
                }

                /**
                 * Gets the value of the sOffset property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getSOffset() {
                    return sOffset;
                }

                /**
                 * Sets the value of the sOffset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setSOffset(Double value) {
                    this.sOffset = value;
                }

                /**
                 * Gets the value of the rule property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link eu.opends.opendrive.data.Rule }
                 *     
                 */
                public eu.opends.opendrive.data.Rule getRule() {
                    return rule;
                }

                /**
                 * Sets the value of the rule property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link eu.opends.opendrive.data.Rule }
                 *     
                 */
                public void setRule(eu.opends.opendrive.data.Rule value) {
                    this.rule = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Double }
                 *     
                 */
                public Double getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Double }
                 *     
                 */
                public void setWidth(Double value) {
                    this.width = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Rule {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="unit" type="{}unit" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Speed {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "max")
        protected Double max;
        @XmlAttribute(name = "unit")
        protected String unit;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setMax(Double value) {
            this.max = value;
        }

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnit() {
            return unit;
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnit(String value) {
            this.unit = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="forward" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="back" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="left" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="right" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Visibility {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "forward")
        protected Double forward;
        @XmlAttribute(name = "back")
        protected Double back;
        @XmlAttribute(name = "left")
        protected Double left;
        @XmlAttribute(name = "right")
        protected Double right;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the forward property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getForward() {
            return forward;
        }

        /**
         * Sets the value of the forward property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setForward(Double value) {
            this.forward = value;
        }

        /**
         * Gets the value of the back property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getBack() {
            return back;
        }

        /**
         * Sets the value of the back property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setBack(Double value) {
            this.back = value;
        }

        /**
         * Gets the value of the left property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getLeft() {
            return left;
        }

        /**
         * Sets the value of the left property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setLeft(Double value) {
            this.left = value;
        }

        /**
         * Gets the value of the right property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getRight() {
            return right;
        }

        /**
         * Sets the value of the right property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setRight(Double value) {
            this.right = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userData" type="{}userData" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="include" type="{}include" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="a" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="b" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="c" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="d" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userData",
        "include"
    })
    public static class Width {

        protected List<UserData> userData;
        protected List<Include> include;
        @XmlAttribute(name = "sOffset")
        protected Double sOffset;
        @XmlAttribute(name = "a")
        protected Double a;
        @XmlAttribute(name = "b")
        protected Double b;
        @XmlAttribute(name = "c")
        protected Double c;
        @XmlAttribute(name = "d")
        protected Double d;

        /**
         * Gets the value of the userData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserData }
         * 
         * 
         */
        public List<UserData> getUserData() {
            if (userData == null) {
                userData = new ArrayList<UserData>();
            }
            return this.userData;
        }

        /**
         * Gets the value of the include property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Include }
         * 
         * 
         */
        public List<Include> getInclude() {
            if (include == null) {
                include = new ArrayList<Include>();
            }
            return this.include;
        }

        /**
         * Gets the value of the sOffset property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getSOffset() {
            return sOffset;
        }

        /**
         * Sets the value of the sOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setSOffset(Double value) {
            this.sOffset = value;
        }

        /**
         * Gets the value of the a property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getA() {
            return a;
        }

        /**
         * Sets the value of the a property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setA(Double value) {
            this.a = value;
        }

        /**
         * Gets the value of the b property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getB() {
            return b;
        }

        /**
         * Sets the value of the b property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setB(Double value) {
            this.b = value;
        }

        /**
         * Gets the value of the c property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getC() {
            return c;
        }

        /**
         * Sets the value of the c property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setC(Double value) {
            this.c = value;
        }

        /**
         * Gets the value of the d property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getD() {
            return d;
        }

        /**
         * Sets the value of the d property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setD(Double value) {
            this.d = value;
        }

    }

}
